start = expression;

expression = term {["+" | "-"] term};

term = factor {["*" | "/"] factor};

factor = exponent {"^" exponent};

exponent = number
       | "(" expression ")"
       | ["+" | "-"] exponent
       ;

number = ? C type double ?;
