start
    = expression
    ;

expression
    = term {("+" | "-") term}
    ;

term
    = factor {("*" | "/") factor}
    ;

factor
    = exponent {"^" exponent}
    ;

exponent
    = "(" expression ")"
    | ("+" | "-") exponent
    | number
    ;

number
    = ? C type double ?
    ;
